PEFramework for loading GTA SA executable
ctnorth/ctnorth pull request #2
Opened 2016-12-12 18:41 UTC by quiret

I wrote the PEFramework library to simply using the PE file format. The library exposes all of the variables inside PE files. Please consider using it and providing feedback to me about things you would like to see improved.

Meow, thx.

2016-12-12 19:01 UTC, ifarbod requested changes
Fix these and I will merge it. Although it can be clang-format'd. 👍

2016-12-12 19:01 UTC, ifarbod commented on Client/Launcher/ExecutableLoader.cpp
> +void ExecutableLoader::LoadSections( void )
Unnecessary void for functions which don't take a parameter.

2016-12-12 19:01 UTC, ifarbod commented on Client/Launcher/ExecutableLoader.cpp
> +void ExecutableLoader::LoadSection( PEFile::PESection& sect )
Spaces between parentheses.

2016-12-12 19:01 UTC, ifarbod commented on Client/Launcher/premake5.lua
> +        "../../Vendor/eirrepo/"
What does it requires from eirrepo?

2016-12-12 19:20 UTC, quiret commented on Client/Launcher/premake5.lua
> +        "../../Vendor/eirrepo/"
It requires rwlist.hpp, MemoryRaw.h, MemoryUtils.h and MemoryUtils.stream.h . Those are being created by PEFramework.

2016-12-12 19:26 UTC, ifarbod approved these changes
Thanks for adhering to our coding conventions.

2016-12-12 20:03 UTC, quiret commented
I will adhere in the future aswell :) If this gets merged I will contribute great tech(tm) in the future aswell.

2016-12-18 06:46 UTC, ifarbod commented
@AppVeyorBot Nice.

2016-12-20 10:28 UTC, closed without merging